src/main/java/com/soongsil/CoffeeChat/CoffeeChatApplication.java
src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/config/swagger/SwaggerConfig.java

fix: CORS err

---

src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/controller/EmailController.java
src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java
src/main/java/com/soongsil/CoffeeChat/controller/RefreshTokenController.java
src/main/java/com/soongsil/CoffeeChat/controller/S3Controller.java
src/main/java/com/soongsil/CoffeeChat/controller/StatusCheckController.java
src/main/java/com/soongsil/CoffeeChat/controller/UserController.java

crossorigin빼고 corsconfig 수정

---

src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
src/test/java/com/soongsil/CoffeeChat/CoffeeChatApplicationTests.java

fix: corsConfig-> add https domain

---

src/main/java/com/soongsil/CoffeeChat/CoffeeChatApplication.java

fix: cors err(remove crossorigin, server annotation)

---

src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java

fix: cors err (allowedMethod방식 나열형으로 변경)

---

src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java

fix: remove eror 124 line

---

src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java

prefix: jwtfilter's location changed in filterchain

---

src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java

- err: prefix -> CORS
- tmp
- #1

prefix : preflight err

---

src/main/java/com/soongsil/CoffeeChat/CoffeeChatApplication.java
src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java

- 비단순 요청이 들어올 때 preflight Options Check 요청을 JWT Filter에서 설정하여주지 않았음
- tmp
- tmp

err fix: cors err by preflight options request

---

.github/workflows/cogo_cicd_gradle.yml

feat: cicd-pipeline

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

loginSuccessHandler : ref redirect url

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

로그인성공시 리디렉트 수정, loginStatus 수정

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

access token, refresh token 발급 로직 수정

---

src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

- reissue API에서 JWT Util이 NULL로 설정되어 있던 문제 해결
- tmp
- #18

reissue API의 오류 수정

---

src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateRequestDto.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

멘토 시간등록 오류 해결

---

src/main/java/com/soongsil/CoffeeChat/controller/RefreshTokenController.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

loginStatus 헤더에 추가

---

src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

- tmp
- tmp
- tmp
프론트엔드 프로토콜 변경 http -> https

fix: client change to https protocol

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

server test

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

- tmp
- tmp
- tmp
- 쿠키 생성로직 변경

set cookie

---

src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

쿠키 바꾸면서 reissue 서비스단 수정

---

src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

test: reissue api실행되는지 로깅

---

src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java

cogo.life 도메인 cors허용 추가

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

change loginsuccess redirect: https:localhost:3000/callback

---

src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java

exposedHeaders 추가 : access, loginStatus

---

src/main/java/com/soongsil/CoffeeChat/CoffeeChatApplication.java

server restart

---

src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

uri 수정 : 프론트 배포 도메인

---

src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java

role changed

---

src/main/java/com/soongsil/CoffeeChat/dto/ResponseMentorListInfo.java

멘토 part 같이 반환
- tmp
- tmp
- tmp

멘토 part 리턴

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

local deploy

---

src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
src/main/java/com/soongsil/CoffeeChat/enums/RequestUri.java

커피챗 신청 controller추가

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

return to deploy domain

---

.gitignore
build.gradle
src/main/generated/com/soongsil/CoffeeChat/entity/QApplication.java
src/main/generated/com/soongsil/CoffeeChat/entity/QClub.java
src/main/generated/com/soongsil/CoffeeChat/entity/QMentee.java
src/main/generated/com/soongsil/CoffeeChat/entity/QMentor.java
src/main/generated/com/soongsil/CoffeeChat/entity/QPossibleDate.java
src/main/generated/com/soongsil/CoffeeChat/entity/QRefresh.java
src/main/generated/com/soongsil/CoffeeChat/entity/QUser.java
src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/config/queryDSL/QueryDSLConfig.java
src/main/java/com/soongsil/CoffeeChat/dto/CreateMentorRequest.java
src/main/java/com/soongsil/CoffeeChat/entity/Application.java
src/main/java/com/soongsil/CoffeeChat/entity/Mentee.java
src/main/java/com/soongsil/CoffeeChat/entity/Mentor.java
src/main/java/com/soongsil/CoffeeChat/entity/PossibleDate.java
src/main/java/com/soongsil/CoffeeChat/entity/User.java
src/main/resources/application.yml
src/test/java/com/soongsil/CoffeeChat/CoffeeChatApplicationTests.java
src/test/java/com/soongsil/CoffeeChat/Mentor/MentorSaveTest.java

queryDSL세팅

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/config/queryDSL/QueryDSLConfig.java
src/main/java/com/soongsil/CoffeeChat/repository/MentorRepository.java

query dsl setting test : 완료

---

src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java

bug fixed: 액세스 토큰 만료시 401 반환

---

src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/test/java/com/soongsil/CoffeeChat/PostTestData/GetMentorList.java

로그인 리다이렉트 도메인 변경 (로컬테스트용)

---

src/main/generated/com/soongsil/CoffeeChat/entity/QPossibleDate.java
src/main/java/com/soongsil/CoffeeChat/entity/PossibleDate.java
src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepositoryImpl.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
src/main/java/com/soongsil/CoffeeChat/service/UserService.java

커피챗 성사 로직 수정 , PossibleDate 필드 변경

---

src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTUtil.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateRequest.java
src/main/java/com/soongsil/CoffeeChat/entity/PossibleDate.java
src/main/java/com/soongsil/CoffeeChat/entity/User.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepository.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepositoryCustom.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepositoryImpl.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java
src/main/java/com/soongsil/CoffeeChat/service/UserService.java
src/test/java/com/soongsil/CoffeeChat/PostTestData/setUserMentorTestData.java

테스트용 토큰 유효기간 수정

---

src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTUtil.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

- #56 토큰 만료시 JWT Filter 무한순회하며 서버에러 발생
- 토큰 만료시 401에러 반환
- 토큰 만료시 JWT Filter 무한순회하며 서버에러 발생
- -> 즉시 401에러 반환

Bug/#56 토큰 만료시 401에러 반환

---

src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTUtil.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

- 코드 정리
- 토큰 만료시 401에러 반환
- 토큰 만료시 401에러 반환 처리 코드 정리

토큰 만료시 401에러 반환

---

src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTUtil.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

- jwt 검증 로직이 잘못되어 모든 토큰에 만료처리를함
- jwt 검증 로직 수정

bug: jwt 검증 로직 수정

---

src/main/java/com/soongsil/CoffeeChat/config/async/AsyncConfig.java

- 커피챗 신청 API 성능 개선
- 커피챗신청 API 비동기처리
- 커피챗신청 API 비동기처리로 응답속도 개선

커피챗신청 API 비동기처리

---

src/main/java/com/soongsil/CoffeeChat/CoffeeChatApplication.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/controller/EmailController.java
src/main/java/com/soongsil/CoffeeChat/email/EmailUtil.java

https:callback으로 redirect

---

.github/workflows/cogo_cicd_gradle.yml
build.gradle
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/config/redis/RedisConfig.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java
src/main/resources/application.yml

- refresh토큰 redis에 저장
- ttl : 1일
- refresh토큰 redis에 저장
- #67

refresh토큰 redis에 저장

---

src/main/java/com/soongsil/CoffeeChat/config/redis/RedisConfig.java

- redis 시크릿값으로 연결하기 추가(redis config)
- redis config: add secrets

redis config: add secrets

---

src/main/java/com/soongsil/CoffeeChat/config/redis/RedisConfig.java

- redis config 시크릿값 설정 수정
- [tmp](fix: redis config's secrets value)

fix: redis config's secrets value

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

- refresh token 저장소 redis로 수정
- TTL : 1일
- 속도 개선작업
- refresh token 저장소 redis로 수정

refresh token 저장소 redis로 수정

---

.github/workflows/cogo_cicd_gradle.yml
build.gradle
src/main/generated/com/soongsil/CoffeeChat/entity/QUser.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/controller/EmailController.java
src/main/java/com/soongsil/CoffeeChat/controller/UserController.java
src/main/java/com/soongsil/CoffeeChat/entity/User.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java
src/main/java/com/soongsil/CoffeeChat/service/UserService.java
src/main/java/com/soongsil/CoffeeChat/util/email/EmailUtil.java
src/main/java/com/soongsil/CoffeeChat/util/sms/SmsUtil.java
src/main/resources/application.yml

- SMS 인증 API 구현 : #75 
- SMS 인증 API 구현
- Cool SMS API를 통해 SMS 인증 구현
- 인증받은 번호를 User엔티티에 저장하는 API 구현

Feat : SMS 인증 API 구현

---

src/main/java/com/soongsil/CoffeeChat/controller/UserController.java

fix : 번호 저장 api swagger 설명수정

---

.github/workflows/cogo_cicd_gradle.yml
build.gradle
src/main/generated/com/soongsil/CoffeeChat/entity/QUser.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/controller/EmailController.java
src/main/java/com/soongsil/CoffeeChat/controller/UserController.java
src/main/java/com/soongsil/CoffeeChat/entity/User.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java
src/main/java/com/soongsil/CoffeeChat/service/UserService.java
src/main/java/com/soongsil/CoffeeChat/util/email/EmailUtil.java
src/main/java/com/soongsil/CoffeeChat/util/sms/SmsUtil.java
src/main/resources/application.yml

번호 저장 api swagger 설명수정

---

src/main/generated/com/soongsil/CoffeeChat/dto/QPossibleDateRequestDto.java
src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateRequestDto.java
src/main/java/com/soongsil/CoffeeChat/entity/PossibleDate.java
src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepositoryImpl.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java

- fix: 커피챗 성사시 active처리 오류 해결
- JPQL문의 조건 부족으로 다른 멘토의 커피챗 시간대가 active되는 문제 해결

fix: 커피챗 성사시 active처리 오류 해결

---

application.log
src/main/java/com/soongsil/CoffeeChat/controller/handler/ApplicationExceptionHandler.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateRequest.java
src/main/java/com/soongsil/CoffeeChat/entity/PossibleDate.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/resources/logback.xml
src/test/java/com/soongsil/CoffeeChat/Concurrency/ConcurrencyTest.java

- Application 서비스 로직에 분산 Lock 로직 도입
- 409 : 예약중, 410 : 이미 예약됨
- Application 컨트롤러에 Exception Handler 추가
- 동시성 이슈 : 분산 Lock으로 해결
- #79

동시성 이슈 : 분산 Lock으로 해결

---

src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
src/main/java/com/soongsil/CoffeeChat/controller/exception/CustomException.java
src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/ApplicationErrorCode.java
src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/MentorErrorCode.java
src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/PossibleDateErrorCode.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateRequest.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationGetResponse.java
src/main/java/com/soongsil/CoffeeChat/entity/Application.java
src/main/java/com/soongsil/CoffeeChat/entity/Mentee.java
src/main/java/com/soongsil/CoffeeChat/enums/RequestUri.java
src/main/java/com/soongsil/CoffeeChat/repository/ApplicationRepository.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
src/test/java/com/soongsil/CoffeeChat/Concurrency/ConcurrencyTest.java

- #95 
- COGO 관련 로직 구현
-  COGO 신청
- 특정 COGO 조회
- 신청 받은 COGO 전체 조회
- API url REST하게 전체 수정
- ERD ver2.0에 맞게 Application에 PossibleDate 추가

feat: COGO 관련 로직

---

src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
src/main/java/com/soongsil/CoffeeChat/dto/MentorUpdateRequestDto.java
src/main/java/com/soongsil/CoffeeChat/entity/User.java
src/main/java/com/soongsil/CoffeeChat/repository/Mentor/MentorRepositoryImpl.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
src/test/java/com/soongsil/CoffeeChat/QueryTest/GetMentorListTest.java

- #97 
- 멘토 세부 정보 수정 개발
- 사진 제외

feat: 멘토 세부 정보 수정

---

src/main/java/com/soongsil/CoffeeChat/dto/MenteeDto.java
src/main/java/com/soongsil/CoffeeChat/entity/Mentee.java

- V2 위한 엔티티 최종수정
- 멘티 엔티티 수정, part타입 enum으로 변경

Ref/#99 멘티 엔티티 수정, part타입 enum으로 변경

---

application.log
src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
src/main/java/com/soongsil/CoffeeChat/controller/UserController.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationGetResponse.java
src/main/java/com/soongsil/CoffeeChat/dto/ChangeUserInfoDto.java
src/main/java/com/soongsil/CoffeeChat/dto/ResponseMentorInfo.java
src/main/java/com/soongsil/CoffeeChat/dto/ResponseMentorListInfo.java
src/main/java/com/soongsil/CoffeeChat/enums/RequestUri.java
src/main/java/com/soongsil/CoffeeChat/repository/ApplicationRepository.java
src/main/java/com/soongsil/CoffeeChat/repository/Mentor/MentorRepository.java
src/main/java/com/soongsil/CoffeeChat/repository/Mentor/MentorRepositoryCustom.java
src/main/java/com/soongsil/CoffeeChat/repository/Mentor/MentorRepositoryImpl.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
src/main/resources/application.yml
src/test/java/com/soongsil/CoffeeChat/Concurrency/ConcurrencyTest.java

- #101 API 전체 점검 후 TODO 작성
- API 전체 점검 후 TODO 작성
- API추가 작성 필요, Query작성 필요, API테스트 필요

Ref/#101 API 전체 점검 후 TODO 작성

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java
src/main/resources/application.yml

- #106 
- 테스트용 토큰 기간 연장, 로그인시 스웨거로 연결
- reissue 요청시 토큰 유효시간 5시간
- 소셜 로그인시 로컬 스웨거로 redirect

[refactor] 테스트용 토큰 기간 연장, 로그인시 스웨거로 연결

---

src/main/java/com/soongsil/CoffeeChat/service/UserService.java
src/main/resources/application.yml

- 멘토 가입시 텅 빈 자기소개 엔티티 연결
- 텅 빈 자기소개 엔티티(Introduction)은 null로 필드들이 구성
- 멘토 가입시 텅 빈 자기소개 엔티티 연결
#110

멘토 가입시 텅 빈 자기소개 엔티티 연결

---

src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
src/main/java/com/soongsil/CoffeeChat/controller/handler/ApiResponseGenerator.java
src/main/java/com/soongsil/CoffeeChat/controller/handler/ApplicationExceptionHandler.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateRequestDto.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateResponseDto.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/resources/application.yml

feat: COGO 생성

---

src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/ApplicationErrorCode.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationMatchResponseDto.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java

- #117 
- COGO 수락/거절 기능 개발
- 이슈 참고

feat: COGO 수락/거절 기능 개발

---

src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java

- #120 
- 매칭된/매칭되지 않은 COGO 조회 기능 개발
- 자세한 내용 이슈 참조

refactor: 매칭된/매칭되지 않은 COGO 조회 기능 개발

---

src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/MentorErrorCode.java
src/main/java/com/soongsil/CoffeeChat/dto/MentorIntroductionUpdateRequestDto.java
src/main/java/com/soongsil/CoffeeChat/dto/MentorIntroductionUpdateResponseDto.java
src/main/java/com/soongsil/CoffeeChat/entity/Introduction.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java

- #122 
- 멘토 자기소개 입력 기능 개발
- PATCH 로 개발

feat: 멘토 자기소개 입력 기능 개발

---

src/main/java/com/soongsil/CoffeeChat/dto/MentorIntroductionUpdateRequestDto.java
src/main/java/com/soongsil/CoffeeChat/entity/Introduction.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java

- #124 
- 멘토 자기소개 원하는 만큼만 수정 가능
- DTO 손봤습니다

fix: 멘토 자기소개 원하는 필드만 수정 가능

---

src/main/java/com/soongsil/CoffeeChat/controller/RefreshTokenController.java
src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/RefreshErrorCode.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

- Reissue 로직 반환값 Base Response에 맞게 수정(#129 )
- Reissue 로직은 body반환값이 없기 때문에, 로직 수행 여부를 반환하였습니다.
- 각 에러 상황에 맞는 에러 Enum클래스 추가
- Reissue 로직 반환값 Base Response에 맞게 수정

ref: Reissue 로직 반환값 Base Response에 맞게 수정(#129)

---

build.gradle
settings.gradle
src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
src/main/java/com/soongsil/CoffeeChat/config/aws/S3Config.java
src/main/java/com/soongsil/CoffeeChat/config/aws/SqsConfig.java
src/main/java/com/soongsil/CoffeeChat/controller/EmailController.java
src/main/java/com/soongsil/CoffeeChat/controller/RefreshTokenController.java
src/main/java/com/soongsil/CoffeeChat/controller/UserController.java
src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/RefreshErrorCode.java
src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/UserErrorCode.java
src/main/java/com/soongsil/CoffeeChat/dto/UserController/MenteeInfoDto.java
src/main/java/com/soongsil/CoffeeChat/dto/UserController/MentorInfoDto.java
src/main/java/com/soongsil/CoffeeChat/dto/UserController/UserInfoDto.java
src/main/java/com/soongsil/CoffeeChat/dto/UserInfoDto.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepository.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java
src/main/java/com/soongsil/CoffeeChat/service/UserService.java
src/main/java/com/soongsil/CoffeeChat/util/email/EmailUtil.java
src/main/resources/application.yml
src/test/java/com/soongsil/CoffeeChat/Concurrency/ConcurrencyTest.java
src/test/java/com/soongsil/CoffeeChat/Mail/EmailServiceTest.java

- 메일인증 비동기처리에서 코드를 제대로 반환하지 않고 있던 문제 해결
- 비동기 처리한 메일전송 기능에서 오류 발생시, 반환값을 확인하는 테스트 코드 작성
#TODO:
- SQS, SES를 연동하여 메일전송 기능 오류 발생시, 재전송 로직 구성 필요
-메일인증 비동기처리 개선 및 안정성 테스트코드 작성
- #133

[Ref] 메일인증 비동기처리 개선 및 안정성 테스트코드 작성 

---

src/main/java/com/soongsil/CoffeeChat/config/aws/SqsConfig.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/util/email/EmailMessage.java
src/main/java/com/soongsil/CoffeeChat/util/email/EmailUtil.java
src/main/resources/application.yml

- SQS연동 밑작업
- SQS 메시지 전송 로직 추가
- 클라이언트 API연동 작업용 로그인 리다이렉트 변경
- 메일 전송 요청시 SQS에 메시지 전달 로직 추가 
- #133

[Feat] 메일 전송 요청시 SQS에 메시지 전달 로직 추가 

---

src/main/java/com/soongsil/CoffeeChat/dto/UserController/MenteeInfoDto.java
src/main/java/com/soongsil/CoffeeChat/dto/UserController/MentorInfoDto.java
src/main/java/com/soongsil/CoffeeChat/dto/UserController/UserInfoDto.java

-  DTO들에 GETTER가 빠져 정보수정 로직 오류 발생-수정완료
-  DTO들에 GETTER가 빠져 정보수정 로직 오류 발생
- #140

[FIX] DTO들에 GETTER가 빠져 정보수정 로직 오류 발생-수정완료(#140)

---

src/main/java/com/soongsil/CoffeeChat/dto/UserGetUpdateDto.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepository.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepositoryCustom.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepositoryImpl.java
src/main/java/com/soongsil/CoffeeChat/service/UserService.java

- 유저 개인정보 반환시, 역할+파트+동아리 함께 반환
- 개인정보 DTO수정
- reissue로직에서 역할 함께 반환
- 유저 개인정보 반환시, 역할+파트+동아리 함께 반환

[REFACTOR]: 유저 개인정보 반환시, 역할+파트+동아리 함께 반환(#145)

---

src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java

- #149 
- 가능시간 request dto list형식으로 변환
- @haesol822 님 요청으로 작업 했습니다.
- 별거 아니라 바로 머지할게요

refactor: 가능 시간 reqeust dto list형식으로 변환

---

src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateResponseDto.java
src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateGetResponseDto.java
src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateRequestDto.java

refactor: 날짜 형식 포맷팅

---

src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java

fix: POST -> PUT

---

src/main/java/com/soongsil/CoffeeChat/dto/UserGetUpdateDto.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepositoryImpl.java

- 개인정보 조회 DTO 필드명 변경 : image -> picture
- 개인정보 조회 DTO 필드 추가 : mentorId (유저가 멘토일시 값존재, 멘티일시 null)
-  개인정보 조회 DTO 필드명 변경 및 추가
- #156

[REFACTOR] 개인정보 조회 DTO 필드명 변경 및 추가

---

src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java
src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepository.java
src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java

- #155 
- 가능시간 추가 `->` 가능시간 갱신
- tmp

refactor: 가능시간 갱신

---

src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java

fix: 경로에 정규표현식 추가

---

src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java

- #166
- Update JWT Expiration Time
- @HI-JIN2 요청으로 연장합니다

refactor: JWT 만료 시간 연장

---

src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
src/main/java/com/soongsil/CoffeeChat/controller/UserController.java
src/main/java/com/soongsil/CoffeeChat/dto/UserGetDto.java
src/main/java/com/soongsil/CoffeeChat/dto/UserUpdateDto.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepository.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepositoryCustom.java
src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepositoryImpl.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
src/main/java/com/soongsil/CoffeeChat/service/UserService.java

- #168 
- API 응답 양식 및 URL PATH 개선
- 이슈 참고
- @HI-JIN2  님 요청으로 수정합니다.

refactor: API 응답 양식 및 URL PATH 개선

---

src/main/java/com/soongsil/CoffeeChat/config/S3Config.java
src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateRequest.java
src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateResponse.java
src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateRequestDto.java
src/main/java/com/soongsil/CoffeeChat/dto/ResponseMentorListInfo.java

- 클라이언트 배포 링크로 로그인 성공시 리다이렉트
- 로그인 성공시 배포링크로 redirect
- #170

REF: 로그인 성공시 배포링크로 redirect(#170)

---

src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java

refactor: 가능시간 조회 기간 2주로 설정

---

src/main/java/com/soongsil/CoffeeChat/controller/ReportController.java
src/main/java/com/soongsil/CoffeeChat/dto/ReportDto.java
src/main/java/com/soongsil/CoffeeChat/entity/Report.java
src/main/java/com/soongsil/CoffeeChat/enums/ReportReason.java
src/main/java/com/soongsil/CoffeeChat/enums/ReportStatus.java
src/main/java/com/soongsil/CoffeeChat/enums/RequestUri.java
src/main/java/com/soongsil/CoffeeChat/repository/ReportRepository.java
src/main/java/com/soongsil/CoffeeChat/service/ReportService.java

- 신고하는 기능 추가
- 신고 엔티티, enum, 컨트롤러~레포 생성
- 신고하기 기능 추가
- #175

[FEAT] 신고하기 기능 추가

---

src/main/java/com/soongsil/CoffeeChat/entity/User.java
src/main/java/com/soongsil/CoffeeChat/repository/ApplicationRepository.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java

- #179 
- COGO 멘티 조회 가능하게 수정
- User에 isMentor(), isMentee() 함수 추가
- ApplicationService에서 COGO 조회 시 활용

FIX: User 역할에 따른 Application 조회 로직 간소화

---

src/main/java/com/soongsil/CoffeeChat/controller/UserController.java
src/main/java/com/soongsil/CoffeeChat/service/UserService.java

- #180 
- 탈퇴하기 기능 구현
- hard delete로 구현

feat: 유저 탈퇴 API 구현

---

src/main/java/com/soongsil/CoffeeChat/aspect/ApplicationCleanupAspect.java
src/main/java/com/soongsil/CoffeeChat/controller/handler/ApplicationExceptionHandler.java
src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateGetResponseDto.java
src/main/java/com/soongsil/CoffeeChat/entity/Application.java
src/main/java/com/soongsil/CoffeeChat/entity/PossibleDate.java
src/main/java/com/soongsil/CoffeeChat/repository/ApplicationRepository.java
src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepository.java
src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepositoryImpl.java
src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java
src/main/resources/application.yml

- #183 
- 코고 신청 로직 변경
- @sunnny619 님 요청으로 수정하였습니다.
- ApplicationCleanupAspect 추가해서, 시간 지난 코고 삭제하게 했습니다.

REFACTOR: COGO 신청 로직 변경

---

src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java

- #189 
- 파트별 멘토 리스트 조회, 멘토 상세 정보 조회 토큰 해제
- 멘토 상세 정보 조회 API, 파트별 멘토 리스트 가져오기 API 토큰 해제했습니다.

REFACTOR: 파트별 멘토 리스트 조회, 멘토 상세 정보 조회 토큰 해제

---

src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
src/main/java/com/soongsil/CoffeeChat/controller/RefreshTokenController.java
src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java
src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java

[FEAT] 모바일용 토큰 재발급 API 

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java
src/main/java/com/soongsil/CoffeeChat/enums/PartEnum.java
src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepositoryCustom.java
src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepositoryImpl.java
src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java

- 모바일 파트 추가, 멘토링 시간대 삭제 기능 추가
-모바일 파트 추가, 멘토링 시간대 삭제 기능 추가

[FIX] 모바일 파트 추가, 멘토링 시간대 삭제 기능 추가

---

src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java
src/main/java/com/soongsil/CoffeeChat/service/UserService.java

- #198 
- 모바일 인증 로직 수정
- 새로 가입하는 유저면 role_user, 기존 유저면 기존에 갖고 있던 role값을 토큰에 넣도록 수정

bug: 모바일 인증 로직 수정

---

src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
src/main/java/com/soongsil/CoffeeChat/dto/MentorIntroductionGetUpdateResponseDto.java
src/main/java/com/soongsil/CoffeeChat/service/MentorService.java

- #200 
- 토큰으로 멘토 자기소개 조회
- 토큰으로 멘토 본인의 자기소개 항목 4개를 조회

 feat: 토큰으로 멘토 자기소개 조회

---

src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java

cookie 생성 도메인 변경

---

.github/workflows/cogo_cd.yml

close #208 
- 도커 로그 영속화
- ec2 디렉터리에 도커 컨테이너 로그 저장

ci: 도커 log 영속화

---

.github/workflows/cogo_cd.yml
src/main/resources/application.yml

Ci/207 cicd 관련 오류 수정

---

.github/workflows/cogo_cd.yml

ci: 누락된 환경변수 추가

---

src/main/java/com/soongsil/CoffeeChat/CoffeeChatApplication.java
src/main/java/com/soongsil/CoffeeChat/config/CorsMvcConfig.java
src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java

- #207 
- 서버 마이그레이션에 대한 cors 수정
- tmp

fix: 서버 마이그레이션에 대한 cors 수정

---

.github/workflows/cogo_cd.yml

ci: ADMIN_PASSWORD 추가

---

src/main/java/com/soongsil/CoffeeChat/domain/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/domain/service/RefreshTokenService.java
src/main/java/com/soongsil/CoffeeChat/domain/service/UserService.java
src/main/java/com/soongsil/CoffeeChat/global/security/handler/CustomSuccessHandler.java
src/main/java/com/soongsil/CoffeeChat/global/security/jwt/JwtUtil.java
src/main/java/com/soongsil/CoffeeChat/global/security/oauth2/CustomOAuth2UserService.java
src/main/java/com/soongsil/CoffeeChat/infra/admin/service/AdminService.java
src/main/java/com/soongsil/CoffeeChat/infra/sms/SmsUtil.java

- #223 
- cogo 거절 메세지 추가
- cogo 수락 메세지 수정
- tmp

chore: cogo 메세지 추가 및 수정

---

src/main/resources/application.yml

chore: ddl-auto none

---

src/main/java/com/soongsil/CoffeeChat/domain/controller/RefreshTokenController.java
src/main/java/com/soongsil/CoffeeChat/domain/controller/UserController.java
src/main/java/com/soongsil/CoffeeChat/domain/dto/UserConverter.java
src/main/java/com/soongsil/CoffeeChat/domain/dto/UserResponse.java
src/main/java/com/soongsil/CoffeeChat/domain/service/UserService.java

refactor: 2FA code 래핑

---

src/main/java/com/soongsil/CoffeeChat/domain/dto/MenteeConverter.java
src/main/java/com/soongsil/CoffeeChat/domain/dto/MenteeResponse.java
src/main/java/com/soongsil/CoffeeChat/domain/dto/MentorConverter.java
src/main/java/com/soongsil/CoffeeChat/domain/dto/MentorResponse.java

remove: 멘토 멘티 가입 불필요 응답 필드 제거

---

src/main/java/com/soongsil/CoffeeChat/domain/controller/PossibleDateController.java
src/main/java/com/soongsil/CoffeeChat/domain/service/PossibleDateService.java

chore: PossibleDate PUT 으로 변경

---

src/main/java/com/soongsil/CoffeeChat/domain/dto/PossibleDateConverter.java

fix: PossibleDate Mentor 연관관계 설정

---

src/main/java/com/soongsil/CoffeeChat/domain/controller/RefreshTokenController.java
src/main/java/com/soongsil/CoffeeChat/domain/dto/MobileTokenResponse.java
src/main/java/com/soongsil/CoffeeChat/domain/entity/User.java
src/main/java/com/soongsil/CoffeeChat/domain/entity/enums/UserAccountStatus.java
src/main/java/com/soongsil/CoffeeChat/domain/service/ApplicationService.java
src/main/java/com/soongsil/CoffeeChat/global/security/oauth2/CustomOAuth2UserService.java
src/main/java/com/soongsil/CoffeeChat/infra/sms/SmsUtil.java

fix: 삭제된 회원 중복 가입 오류 수정

---

src/main/java/com/soongsil/CoffeeChat/domain/service/AuthService.java
src/main/java/com/soongsil/CoffeeChat/global/security/SecurityConfig.java

chore: 시큐리티 허용 api 경로에 auth 경로 추가

---

src/main/java/com/soongsil/CoffeeChat/domain/repository/User/UserRepository.java

fix: 삭제된 유저 포함 조회 sql 오류 수정

---

build.gradle

build: websocket & stomp 의존성 추가

---

src/main/java/com/soongsil/CoffeeChat/domain/mentor/enums/ClubEnum.java

chore: ClubEnum 수정 (gdsc -> gdgoc)

---

src/main/java/com/soongsil/CoffeeChat/global/security/SecurityConfig.java

- cors 정책 위반 수정
- cors 허용 헤더 수정
- tmp

fix: cors 허용 헤더 변경
